version: '2'

services:
  # RabbitMQ
  rabbit:
    hostname: rabbit
    image: rabbitmq:3.6.0
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"  # we forward this port because it's useful for debugging
      - "15672:15672"

  # Worker
  worker:
    build:
      context: .
    environment:
      - ENV=dev
    command: ./start_celery.sh
    links:
      - rabbit
    depends_on:
      - rabbit
  flower:
    build:
      context: .
    environment:
      - ENV=dev
    command: ./start_flower.sh
    links:
      - rabbit
    depends_on:
      - rabbit

    ports:
      - "5555:5555"
